### ISSUE TITLE
Data tables in feature files shows errors when extra data is present after them 

### ISSUE THREAD

**Issue by nicodeslandes** [reqnroll/Reqnroll.Rider#12]
The Rider plugin is show squigglies when some text is added after data tables in feature files:
![image](https://github.com/reqnroll/Reqnroll.Rider/assets/2887884/efdde807-ed18-4d41-94fe-7cfe11da6be3)

This is quite limiting, as we're using this quite extensively in our project to provide additional information to the tables in the feature file.

2 things to note:
* the Reqnroll library is perfectly fine with that, the test pass as expected.
* the Visual Studio plugin is also ok with these, and does not show any errors

Versions used:
* Nuget: Reqnroll.xUnit 2.0.0, Reqnroll 2.0.0
* Plugin: Reqnroll.Rider 2024.1.5
* Rider: 2024.1.2

**Comment by Socolin** [comment]
the problem seems to be that comments are not interpreted as comments after a table.

**Comment by nicodeslandes** [comment]
Yes
I've got a branch that fixes some of the issues: https://github.com/nicodeslandes/Reqnroll.Rider/tree/data-table-parsing

![image](https://github.com/reqnroll/Reqnroll.Rider/assets/2887884/3b1a3357-7ddf-4b00-9e34-1afd75cd540a)



But I've just noticed a bug with this. In that case, if a comment is present the parser stops processing the rest of the table

I'm looking into it still

**Comment by nicodeslandes** [comment]
[https://github.com/reqnroll/Reqnroll.Rider/pull/13/commits/357d6ed041f16c6eb9d56738991d8efb0217ff14](this) fixed the issue with continuing the parsing after a trailing comment
