### ISSUE TITLE
New Reqnroll projects are not using the specified .NET version

### ISSUE THREAD

**Issue by initfrank** [reqnroll/Reqnroll.Rider#15]
When I try to create a new Reqnroll project, I can specify which .NET version I would like to use.

![image](https://github.com/reqnroll/Reqnroll.Rider/assets/18430092/bb5d643e-7696-47af-a389-9373ce889eae)

However, when I access the project file, I see that the .NET version is .NET 6

![image](https://github.com/reqnroll/Reqnroll.Rider/assets/18430092/915d64c2-dfbd-4559-a093-9d6e566fee6b)

Same thing happens when trying to select .NET 8

**Comment by Socolin** [comment]
It should be fixed in next version
