### ISSUE TITLE
Incompatibility with versions of Rider higher than 2024.1.4

### ISSUE THREAD

**Issue by ajeckmans** [reqnroll/Reqnroll.Rider#16]
Apparently there is an incompatibility with versions of Rider higher than 2024.1.4. The marketplace now lists a version range up to 2024.1.4 even though the plugin does not specify an upper limit. @Socolin did you perhaps get an email from the Jetbrains Marketplace about the incompatibility (you should have). Is this something we can fix for you?

Because I mainly use the EAP as a daily driver to ensure colleagues won't run into issues, but it is quite annoying to not have this plugin working :D

**Comment by Socolin** [comment]
> Apparently there is an incompatibility with versions of Rider higher than 2024.1.4. The marketplace now lists a version range up to 2024.1.4 even though the plugin does not specify an upper limit. @Socolin did you perhaps get an email from the Jetbrains Marketplace about the incompatibility (you should have). Is this something we can fix for you?
> 
> Because I mainly use the EAP as a daily driver to ensure colleagues won't run into issues, but it is quite annoying to not have this plugin working :D

I did not get an email. Every EAP it's the same the plugin need to be updated and recompile with the latest version (it's using too many feature and at every update at least 1 small things break)

I have few plugins and updating them take me a full evening each time, so I generally wait until a few EAP are available to avoid having to do the works multiple times.

PR are welcome, or I'll do it eventually.

**Comment by ajeckmans** [comment]
Ok, because the people over at Jetbrains told me that if you leave the plugin unbounded they will check for breaking API changes for the plugin and send the owner an email informing about what has changed. I will ask them why this is not happening

**Comment by Socolin** [comment]
The plugin version is not unbounded

**Comment by Socolin** [comment]
If this help, here how the plugin is currently published
![image](https://github.com/reqnroll/Reqnroll.Rider/assets/539620/31a89e64-5a2c-4804-8afe-cad733ec2919)

**Comment by ajeckmans** [comment]
But we made that change a while ago where it would be unbounded right? So only a minimum version is specified.

**Comment by ajeckmans** [comment]
So I thought this change would make it unbounded: https://github.com/SpecFlowOSS/SpecFlow.Rider/issues/202
If it did not I'll see if I can get more info on why it is not working properly. The whole reason for that change was to automatically support new versions of Rider so long as the plugin verifier says it is compatible.

**Comment by Socolin** [comment]
I reverted this, it was causing too much issue and people did not notice there were on a version not supported.

This is currently causing issues for people that think the specflow extension is buggy on 2024.1 and did not see the switch to reqnroll extension and at first when I did the switch there were 2 plugins suggested for specflow, I had to configure this extension as incompatible with the specflow one.

From what I read it's recommended to remove the bound for simple extensions that may work as-is in the next version, but for this kind of extension something breaks and needs a bit of rework every time I don't see the interest.

**Comment by ajeckmans** [comment]
Ah right, so the plugin won't be automatically disabled on the users' end?

The change was mainly there so that you wouldn't need to do a retarget every time Rider gets a new version. But I guess I'll have to learn to do that work for you :)

**Comment by Socolin** [comment]
One way to keep the plugin up-to-date automatically would be to have a GitHub action that rebuild it daily targeting the latest EAP, so as long as it's still compatible it'll be available through the .zip (Or maybe using another publish channel) and when the build fail at least I would not have to play with the version number to take a quick look.

I would really appreciate if there was some kind of dependabot for rider / inteliji plugin, each time checking the version for everything (rdgen, inteliji, resharper, gradle, jdk) is very time consuming and really not fun.

**Comment by Socolin** [comment]
The update for Rider 2024.2 is finally available, it'll be available in few day, or is already available to be installed manually here

https://github.com/reqnroll/Reqnroll.Rider/actions/runs/10104452223

**Comment by Drew99Kt** [comment]
@Socolin i tried this build from the pipe line but it gives me a error saying its not compatible with 2024.1.4 rider. I was able to rebuild the project and specify 2024.1.4 rider and it seems to work.  I'm not seeing a rider 2024.2

**Comment by Socolin** [comment]
The update for 2024.2 is now available in the marketplace. So you should be able to update it from the Plugins window in Rider.
