### ISSUE TITLE
Feature tests are not detected in Rider at all with latest updates.

### ISSUE THREAD

**Issue by vishalk0908** [reqnroll/Reqnroll.Rider#18]
Feature tests are not detected in Rider at all with the latest updates.

**Comment by ajeckmans** [comment]
Are you experiencing the same issues as mentioned in #1?

**Comment by Drew99Kt** [comment]
There is a open issue ticket here @vishalk0908 
https://github.com/reqnroll/Reqnroll.Rider/issues/1

I think this is probably duplicate issue ticket.

**Comment by vishalk0908** [comment]
Yes, it's the same issue, I will close this now.
