### ISSUE TITLE
Missing .NET 7 and .NET8 target framework

### ISSUE THREAD

**Issue by jordancp1** [reqnroll/Reqnroll.Rider#5]
I installed the [latest](https://github.com/reqnroll/Reqnroll.Rider/actions/runs/8388002321) version in 2024.1.EAP 9 Rider. 

I cannot select .NET frameworks higher than 6 in Reqnroll project creation screen:
![image](https://github.com/reqnroll/Reqnroll.Rider/assets/149678735/be5835d3-5a83-4d84-9b98-d6cc65c0ea4d)

If I try to select any other project type the newest .NET versions are supported:
![image](https://github.com/reqnroll/Reqnroll.Rider/assets/149678735/357f752e-82ed-4950-8228-d5c4d954a705)

Is .NET 7 and 8 support not yet implemented?

**Comment by gasparnagy** [comment]
It seems these options were missing from the new project template. I have added them now. 

Thy with the package produced by the build https://github.com/reqnroll/Reqnroll.Rider/actions/runs/8390734971 once it is ready and reopen the issue if you still see problems.
