### ISSUE TITLE
With Installed PlugIn in Rider 2024.1 RC  File Insert is broken

### ISSUE THREAD

**Issue by DerAlbertCom** [reqnroll/Reqnroll.Rider#6]
New File in Solution View, with installed and enabled Reqnroll Plugin the C# specific file templates are missing.

![image](https://github.com/reqnroll/Reqnroll.Rider/assets/136992/2f23367c-4489-4696-81f7-5cc4b9323e8e)

With the Plugin Disabled., they show up.

![image](https://github.com/reqnroll/Reqnroll.Rider/assets/136992/43ac82ee-503b-4719-8914-aa006136f2f7)

**Comment by Socolin** [comment]
I'll be fix with the next version, I don't know when I will publish it yet but fix is available in git and you can already download a build from github actions

https://github.com/reqnroll/Reqnroll.Rider/actions/runs/8641667432

**Comment by darlov** [comment]
I've got the same issue. I think the issue is connected to the version of `JetBrains.Rider.SDK` package. I've tried change the version to `2024.1.0` in [Plugin.props](https://github.com/reqnroll/Reqnroll.Rider/blob/main/src/dotnet/Plugin.props) and it's working correctly.

**Comment by DerAlbertCom** [comment]
@Socolin great, will try that.

**Comment by DerAlbertCom** [comment]
Works...
