### ISSUE TITLE
Rider cannot start after installing the Reqnroll for Rider plugin

### ISSUE THREAD

**Issue by peter-nguyen-contemi** [reqnroll/Reqnroll.Rider#7]
As the title says, please refer to the error message below.

![image](https://github.com/reqnroll/Reqnroll.Rider/assets/133377780/7c7848db-39a0-426c-96a1-a6099bb68a60)

JetBrains Rider version: 2024.1
Plugin version: 2024.1.1

I also have SpecFlow for Rider version 1.23.6 installed.

I tried to manually delete the plugin from the Rider installation directory but I could not find the plug in folder. Now I cannot start JetBrains Rider. Please help.

**Comment by ajeckmans** [comment]
Check the paths mentioned in https://www.jetbrains.com/help/rider/Directories_Used_by_the_IDE_to_Store_Settings_Caches_Plugins_and_Logs.html
The issue is that you have both specflow and Reqroll plugin installed. Remove either one.

**Comment by peter-nguyen-contemi** [comment]
Thanks, @ajeckmans. I can locate the plugin directory but cannot find anything like `reqnroll` or something indicating that it's the reqnroll plugin. Could you please tell what the plugin folder name would be?
![image](https://github.com/reqnroll/Reqnroll.Rider/assets/133377780/110f6aa6-d9fe-4d80-8f87-ea6b0b8619c5)

**Comment by ajeckmans** [comment]
@peter-nguyen-contemi If you installed Rider through the Jetbrains Toolbox I think the plugin is located in a folder similar to this `C:\Users\<your username>\AppData\Roaming\JetBrains\Rider2024.1\plugins`. The reqnroll one will be named `reqnrollriderplugin`. 
As @DerAlbertCom said, they're not compatible. 

Having said that.. The same filetype registered should not be an issue. It should generate a reportable error at most, but not prevent Rider from opening. This seems like a regression in Rider. Might be worthwhile to open a ticket on Jetbrains youtrack about duplicate registration of a filetype by two plugins crashing the IDE and leaving you in a state where you have to manually go in and fix it.

**Comment by Socolin** [comment]
I think we should declare the plugin incompatible with the specflow one to avoid this problem.

I'll try to check this later today to avoid more people having problems with this.

https://plugins.jetbrains.com/docs/intellij/plugin-compatibility.html#declaring-incompatibility-with-module

**Comment by peter-nguyen-contemi** [comment]
Thanks @ajeckmans, I have located and deleted the plugin folder. I turned out that the plugin was not installed in `C:\Users\<user>\AppData\Local\Programs\Rider\plugins`, it was actually in `C:\Users\<user>\AppData\Roaming\JetBrains\Rider2024.1\plugins` as pointed out in your post.

**Comment by Socolin** [comment]
I added the config to mark this plugin incompatible with specflow
