### ISSUE TITLE
Run tests from Reqnroll files

### ISSUE THREAD

**Issue by paulgill81** [reqnroll/Reqnroll.Rider#8]
Icon not visible in Rider to run individual tests. I can run the whole feature file.

i.e. not icon is visible in the gutter to click Run/Debug on an individual test.

It appears to be and issue when the Gherkin plugin is also installed.

**Comment by Socolin** [comment]
Do you have any error in `backend.log` related to this ?

Also can you try the last build available here ? https://github.com/reqnroll/Reqnroll.Rider/actions/runs/9163885063

**Comment by leofrances-flowbird** [comment]
It works for me with last build, thanks :+1: 

Do you know when a new version of the plugin will be published on Jetbrains Marketplace?

**Comment by Otiel** [comment]
No error in `backend.log`, and I confirm that this build fixes this issue. 🥳

**Comment by Socolin** [comment]
I published the new version, it should be available tomorrow or monday I think

**Comment by Socolin** [comment]
It's now available

**Comment by ajeckmans** [comment]
I did not even miss these until they were back :) It is working correctly in our projects. Thanks!
